//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Satici()
        {
            this.TedarikciBorcOdemes = new HashSet<TedarikciBorcOdeme>();
        }
    
        public int saticiId { get; set; }
        public string kullaniciAdi { get; set; }
        public string parola { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TedarikciBorcOdeme> TedarikciBorcOdemes { get; set; }
    }
}
