//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SepetUrun
    {
        public int sepetUrunId { get; set; }
        public int sepetId { get; set; }
        public Nullable<int> urunBarkod { get; set; }
        public Nullable<int> satisMiktar { get; set; }
        public Nullable<double> urunAnlikFiyat { get; set; }
    
        public virtual Sepet Sepet { get; set; }
    }
}
