//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Irsaliye
    {
        public int irsaliyeNo { get; set; }
        public int tedarikciNo { get; set; }
        public int urunKod { get; set; }
        public int urunBarkod { get; set; }
        public int miktar { get; set; }
        public double birimGirdiFiyat { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual Tedarikci Tedarikci { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
