//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisVeresiye
    {
        public int satisId { get; set; }
        public int musteriNo { get; set; }
        public int sepetId { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Sati Sati { get; set; }
        public virtual Sepet Sepet { get; set; }
    }
}
