//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TedarikciBorcOdeme
    {
        public int saticiId { get; set; }
        public int tedarikciNo { get; set; }
        public Nullable<double> odenenMiktar { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual Satici Satici { get; set; }
        public virtual Tedarikci Tedarikci { get; set; }
    }
}
